### ISSUE TITLE
Error in Shadowlands Prepatch

### ISSUE THREAD

**Issue by Kainie85** [idiomatic/HandyNotes_Achievements#12]
![1](https://user-images.githubusercontent.com/27585051/96338495-c4e9f700-108e-11eb-9c11-9421a7538e07.png)

**Comment by idiomatic** [comment]
Thank you for your report.  Unfortunately, I've left WoW so have ~~no~~ limited ability to maintain this add-on.

**Comment by JanGalek** [comment]
Hi @idiomatic , can you just do CR and merge ? thank you
