### ISSUE TITLE
git submodule some of the things

### ISSUE THREAD

**Issue by idiomatic** [idiomatic/HandyNotes_Achievements#21]
ala LibQTip.

**Comment by idiomatic** [comment]
alas, the Ace3 suite is in Subversion.

**Comment by JanGalek** [comment]
https://github.com/wowace-clone/Ace3 ;)

**Comment by idiomatic** [comment]
will splinter InSeason and InstanceLocations at a later time (or as they say, "in post").

**Comment by idiomatic** [comment]
Pardon the redundancy, but because of the Subversion-origination of authentic Ace3, and authenticity-concerns of @wowace-clone, we may wish to revert #23.

**Comment by JanGalek** [comment]
I'm reverting it ;) and updating Ace3 ;)

**Comment by idiomatic** [comment]
Reverting, or shifting the dependency elsewhere?

### opinion:
Sometimes the complexity added by using libraries or frameworks exceeds the complexity provided.  I'm personally a fan of studying how the library or framework works, and extracting -- or in essence freezing -- the important, useful bits.  While the underlying WoW runtime API may change, so may the library or framework API, jeopardizing the value-proposition of the "middleman".  The development of HandyNotes_Achievements evolved to be increasingly conservative as a defense to API-drift and abstraction-impedance.

In my opinion, using libraries, frameworks, and even submodules is complexity of dubious benefit and each exception should be scrutinized.  My immediate concern is that the Makefile's blind `git submodule update` on publish (a hack around the complexity I reluctantly added to submodularize AchievementLocations) is increasingly risky as the dependence of submodules _whose API may change without warning_ increases.
