### ISSUE TITLE
release 0.5.0

### ISSUE THREAD

**Issue by idiomatic** [idiomatic/HandyNotes_Achievements#24]
- [x] confirm 2cbaeeae36525eaa2b318704dbc3832366ea1d8e (or later) [archive](https://github.com/idiomatic/HandyNotes_Achievements/actions/runs/323061891) works with WoW client [@JanGalek or volunteer]
- [x] bump version to 0.5.0
- [x] add ceremonial CHANGELOG.txt entry
- [x] _beta_ release to CurseForge [@idiomatic, to monitor new deploy tech]
- [x] release to CurseForge [@JanGalek, via GitHub Actions]

**Comment by JanGalek** [comment]
Shadowlands not launch 2020-10-27 ;), it was postponed. Shadowlands will be this year, but nobody know when (COMING 2020).

**Comment by idiomatic** [comment]
decoupling from Shadowlands then.

(before expansions is a good time for players to "catch up" on achievements.)

**Comment by JanGalek** [comment]
I'll test actual master if works with WoW Client ;)

**Comment by JanGalek** [comment]
You can automate release for CurseForge - https://authors.curseforge.com/knowledge-base/projects/3451-automatic-packaging (so you can work only there on github :) )

**Comment by idiomatic** [comment]
It's good to know there's another CurseForge-specific option.

For now, I'm happy with the (general-purpose "marketable" skills) GitHub Actions solution, based on https://github.com/BigWigsMods/packager.

---

On the topic of release management: I do have a minor concern whether the publish action should force updating latest submodules before archiving.  If it's automatic (as it is [currently coded](https://github.com/idiomatic/HandyNotes_Achievements/blob/781581f28c40b0c561c260b429f0ce8a9334efe1/.github/workflows/publish_curseforge.yml#L46)), it is one fewer thing to forget to update on regular releases.  On the other hand, it would require "trickery" for forks or branches to override which AchievementLocations or Ace3 versions submodule.  For now, I'll err on the side of being more ~~convenient~~ magical for the majority of the use case.

**Comment by JanGalek** [comment]
ok, for now it'll be better ;)

**Comment by JanGalek** [comment]
You're right with https://github.com/wowace-clone/Ace3 is not actual. so I'm cloning and converting it to git, and I try make automate update :)

**Comment by idiomatic** [comment]
If further discussion, continue on #21?

> You're right with https://github.com/wowace-clone/Ace3 is not actual. so I'm cloning and converting it to git, and I try make automate update :)

**Comment by JanGalek** [comment]
I'm happy that I can confirm that master works with actual version of WoW Client ;)

**Comment by idiomatic** [comment]
Due to increased caution -- thanks to last-minute discovery that GitHub Actions Ubuntu has noticeably obsolete packages -- tonight's release is downgraded to [beta](https://www.curseforge.com/wow/addons/handynotes_achievements/files/3091126).

We shall do a "release" release shortly.

**Comment by idiomatic** [comment]
[0.5.0 beta](https://www.curseforge.com/wow/addons/handynotes_achievements/files/3091126) has exceeded 200 downloads and no new issues have come in, so I'm ok with "release" release.

@JanGalek, do you want to give it a try and "pull the trigger"?

**Comment by JanGalek** [comment]
@idiomatic yes, I want try it :)

**Comment by idiomatic** [comment]
hint: go to [Publish to CurseForge Action](https://github.com/idiomatic/HandyNotes_Achievements/actions?query=workflow%3A%22Publish+to+CurseForge%22) and click the `Run workflow`, and enter `release`.

(I had forgotten there were archives attached to this project within GitHub proper.  is this something worth engineering into the GitHub Actions workflows?)

**Comment by JanGalek** [comment]
I see that you did some changes so I was not sure if I can Run workflow :)

**Comment by idiomatic** [comment]
> I see that you did some changes...

if you mean 51456e27106818a7cc5c3e8e0edbed5aef7e95c1, that was entirely in response to the comment on 93fcfb6bbbe58d9545d4fd1f2408e662ad4dbc12, and inconsequential from code.

> ... I was not sure if I can Run workflow.

Be my guest and try.  I'm eager to see if you have the ability to take over should I get hit by a bus.

**Comment by idiomatic** [comment]
@JanGalek congrats!

**Comment by JanGalek** [comment]
@idiomatic Thank you :)

**Comment by idiomatic** [comment]
One small concern: the release does not have the version number burned into the "zip" archive filename.  Do you think we should add that for releases builds?

It would be challenging as the GitHub Actions workflow does not have the same scriptability or deferability as the Makefile.  The Makefile has the ability to lazily determine the VERSION from the TOC file, and as the Makefile is contained within the repo, it is after the git clone which supplies the TOC file.

Option 1 would be to use some `set-output` from the Makefile and feed that into the workflow's ARCHIVE variable, if the release-type warrants it.

Option 2 would be to omit ARCHIVE from the workflow and just trust the Makefile layer to selectively add version.

**Comment by JanGalek** [comment]
Do you mean for name of zip ? I think it should not be problem, but I can add it ;)

**Comment by idiomatic** [comment]
Manually adding the version to the path is discouraged.  In fact, I want to avoid any uploading of release artifacts.  I've witnessed too many release engineering catastrophes to trust desktop PCs or avoidable manual steps.

**Comment by idiomatic** [comment]
Let me pivot my concern: Is it still customary to have version numbers to the filename of archive WoW AddOns?

If so, I'll own the remedy.

**Comment by JanGalek** [comment]
I see that other addons has version in filename

**Comment by JanGalek** [comment]
We can try automate it, for example when we push tag (postfix alpha/beta will create alpha/beta version and without postfix will create release)

**Comment by idiomatic** [comment]
> We can try [to] automate it.

Now you understand my motivation for continued involvement in this project: practicing CI/CD.

#32

**Comment by idiomatic** [comment]
woot!

![image](https://user-images.githubusercontent.com/190763/97121866-a7480d80-16de-11eb-9a84-f78ca618978e.png)

**Comment by JanGalek** [comment]
yeah, twitch app show you new release, but not alpha/beta it must be downloaded manualy :)
