### ISSUE TITLE
Errors in Shadowlands pre-patch

### ISSUE THREAD

**Issue by sauljaffe** [idiomatic/HandyNotes_Achievements#29]
I'm seeing errors appearing in the chat logs from this add-on, on the only character I'm currently leveling.  The errors started with the pre-patch.  Weirdly, the errors are appearing only in the chat log and not in bugsack.

<img width="548" alt="Screen Shot 2020-10-23 at 6 33 56 PM" src="https://user-images.githubusercontent.com/26287341/97059692-1eef2e80-155f-11eb-95c3-37e787002d00.png">

**Comment by idiomatic** [comment]
dup of #12 and #28.
