### ISSUE TITLE
Error in library.

### ISSUE THREAD

**Issue by Cluuey** [idiomatic/HandyNotes_Achievements#38]
I noticed this error message in my chat log when I zone into the Darkmoon Faire.
It doesn't come up in Bugsack though, not sure why but thought I should let you know. I had a look and didn't notice see other bug reports about it.

```HandyNotes_Achievements Error: ...otes_Achievements\Libs/InSeason-1.1/InSeason-1.1.lua:22: attempt to call field 'GetDate' (a nil value)```

**Comment by idiomatic** [comment]
This has been fixed in the v0.5.0 release.  Please confirm you're using a current version.  If you are current, reopen this issue.

**Comment by Cluuey** [comment]
I thought I had the latest version but it looks like I've got `Version: 0.4.22`.
I think what's happened is I've gone to download the latest file and then my browser has told me I already have a file with that name, so I've assume I've already downloaded it.

Can you add version numbers to the zip files please?

**Comment by idiomatic** [comment]
> Can you add version numbers to the zip files please?

I'm sorry about the v0.5.0 archive being ambiguously named.  It's already fixed for future releases (in commit b6f81f78de67b0e9db4fa6b5d2db37bff7b014cc).
