### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Addonman** [idiomatic/HandyNotes_Achievements#39]
Error occured in: Global
Count: 1
Message: ...s\HandyNotes_BattleForAzerothAchievments_Handler.lua line 58:
   attempt to call global 'GetAtlasInfo' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:58:
      ...s\HandyNotes_BattleForAzerothAchievments_Handler.lua:57
   [string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:115:
      ...s\HandyNotes_BattleForAzerothAchievments_Handler.lua:112
   [string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:179:
      ...s\HandyNotes_BattleForAzerothAchievments_Handler.lua:176
   [string "@HandyNotes_BattleForAzerothAchievments\HandyNotes_BattleForAzerothAchievments_Handler.lua"]:408: (for generator)()
   [string "@HandyNotes\HandyNotes.lua"]:433:
      HandyNotes\HandyNotes.lua:419
   [string "=[C]"]: ?
   [string "@HandyNotes\HandyNotes.lua"]:56:
      HandyNotes\HandyNotes.lua:51
   [string "@HandyNotes\HandyNotes.lua"]:483: ?()
   [string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [string "=[C]"]: ?
   [string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   [string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@TomTom\libs\HereBeDragons\HereBeDragons-2.0.lua"]:269:
      ...dOns\TomTom\libs\HereBeDragons\HereBeDragons-2.0.lua:252
   [string "@TomTom\libs\HereBeDragons\HereBeDragons-2.0.lua"]:299:
      ...dOns\TomTom\libs\HereBeDragons\HereBeDragons-2.0.lua:298

**Comment by idiomatic** [comment]
Sorry, but this error is not in the HandyNotes_Achievements add-on.  What other HandyNotes extensions are you using?
