### ISSUE TITLE
Up to date method to add new achievements

### ISSUE THREAD

**Issue by Psykotik** [idiomatic/HandyNotes_Achievements#51]
Hello, I really like this addon and the way it displays achievements, but it is missing a lot of expansions (pandaria was the last I think ?).
It seems from your previous messages you are maybe not playing anymore or don't want to invest time in it, but you are still answering questions and I think it's cool.
I've red that there is two method to update data, from a coffee script with the google spreadsheet, and an other, you call "Source of truth" but I don't really get it what it was.
Do you mind if I try to add missing achievement, and explain to me what is the latest method to do so, because i'm a little confused (and I'm pretty confident in the fact it's not writing manually the LUA from scratch ... or it is ?)

Thanks in advance if you take time to explain it to me!

**Comment by idiomatic** [comment]
The CoffeeScript to scrape from Google Sheets was (derisively) clever.  It has been disabled but it remains in the master branch for reference.  The spreadsheet remains as well, and is also not integrated into the build process.

I find maintaining large amounts of data encoded in Lua (or JSON or XML...) to be tedious, but was convinced that "magic" scripts using evolving APIs for finicky applications to be worse.

Therefore, for future-maintainer-compatiblity, we decided that Lua is the place to put achievement locations.

I'm not playing WoW anymore.  I'm also coding only about 5% as before, and mostly in Swift.

**Comment by Psykotik** [comment]
Ok thanks for the information, so the best way in your opinion is to go the old fashinoned way by adding lines in the LUA files in https://github.com/idiomatic/AchievementLocations ? 
For sure it is tedious, but at least it can be fine tuned to be sure every information is at the right place. I saw you granted me push access to the AchievementLocation repo, thanks !

**Comment by idiomatic** [comment]
If one replaces "best" with "accepted", then yes, add lines of Lua data into the AchievementLocations submodule.

I have no expectation of "back-porting" the data into the relic spreadsheet.
