### ISSUE TITLE
Error chat wow bfa 8+

### ISSUE THREAD

**Issue by axnd3r** [idiomatic/HandyNotes_Achievements#6]
Hi, u can fix this problem or update addon?

flooded into the chat:
"HandyNotes_Achievements Error: ...otes_Achievements\Libs/InSeason-1.0/InSeason-1.0.lua:24: attempt to call global 'CalendarGetDate' (a nil value)"

**Comment by idiomatic** [comment]
~~Thank you for your request.  This add-on is abandoned by the author until certain WoW Classic milestones have been reached.~~ fixed in v0.4.20.
