### ISSUE TITLE
Bug for 8.0.1 In case someone picks it back up

### ISSUE THREAD

**Issue by chelpixie** [idiomatic/HandyNotes_Achievements#7]
HandyNotes_Achievements Error: ...otes_Achievements\Libs/InSeason-1.0/InSeason-1.0.lua:24: attempt to call global 'CalendarGetDate' (a nil value)

**Comment by idiomatic** [comment]
~~Thank you for your request.  This add-on is abandoned by the author until certain WoW Classic milestones have been reached.~~ fixed in v0.4.20.
