### ISSUE TITLE
Let me use it in 8.x version

### ISSUE THREAD

**Issue by noadtome** [idiomatic/HandyNotes_Achievements#8]
I do not want any feature updates. Please just make it available in 8.x version.
PLEASE!

**Comment by idiomatic** [comment]
~~Thank you for your request.  This add-on is abandoned by the author until certain WoW Classic milestones have been reached.~~ fixed in v0.4.20.

**Comment by noadtome** [comment]
Thank you for your reply.
But can't anyone else modify it so I can use it in 8.x? Is it too difficult?
I really need this add-on...

**Comment by noadtome** [comment]
@idiomatic Wow! I just saw your update for 8.x.
You don't know how much I appreciate this update. Like air, people don't normally care about it at all, but this add-on is what I do when it's gone. I don't know how many people are using this add-on, but what's clear is that users will be very grateful to you even though they don't say anything.
Thank you very much. Thank you in my heart.
